# Generated by Django 2.2.16 on 2022-02-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220204_0346'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='prevent_self_subscription',
        ),
    ]
