# Generated by Django 2.2.16 on 2022-01-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220125_1104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingregient',
            new_name='Ingredient',
        ),
    ]
