# Generated by Django 2.2.16 on 2022-01-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20220125_1423'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientRecipe',
            new_name='RecipeIngredient',
        ),
        migrations.RenameModel(
            old_name='TagRecipe',
            new_name='RecipeTag',
        ),
    ]
