# Generated by Django 2.2.16 on 2022-01-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20220125_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeusercart',
            options={'verbose_name': 'Список покупок/рецепт', 'verbose_name_plural': 'Списки покупок/рецепт'},
        ),
        migrations.AddConstraint(
            model_name='recipetag',
            constraint=models.UniqueConstraint(fields=('recipe', 'tag'), name='unique_list'),
        ),
    ]
