# Generated by Django 2.2.16 on 2022-01-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20220126_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipes/images', verbose_name='Картинка'),
        ),
    ]
