# Generated by Django 2.2.16 on 2022-03-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20220201_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeusercart',
            options={'ordering': ['-id'], 'verbose_name': 'Список покупок/рецепт', 'verbose_name_plural': 'Списки покупок/рецепт'},
        ),
    ]
