# Generated by Django 2.2.16 on 2022-03-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_auto_20220314_0608'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipeuser',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_recipeusercart'),
        ),
    ]
