# Generated by Django 2.2.16 on 2022-01-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220125_2105'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_list',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('subscriber', 'is_subscribed')},
        ),
    ]
