# Generated by Django 2.2.16 on 2022-01-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220127_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True, verbose_name='Код подтверждения'),
        ),
    ]
