# Generated by Django 2.2.16 on 2022-02-03 12:54

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220203_1234'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, subscriber=django.db.models.expressions.F('is_subscribed')), name='prevent_self_subscription'),
        ),
    ]
