# Generated by Django 2.2.16 on 2022-03-13 11:31

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220213_1505'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, following=django.db.models.expressions.F('follower')), name='prevent_self_subscription'),
        ),
    ]
